version: '3.8'

services:
  # Application AppSenelec
  app-senelec:
    image: zigfreak/appsenelec:latest
    container_name: app-senelec
    ports:
      - "8080:8080"
    environment:
      # Configuration de la base de données
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/senelec
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      
      # Configuration JPA
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      
      # Configuration de l'application
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      
      # Configuration Swagger
      - SPRINGDOC_API_DOCS_PATH=/api-docs
      
      # Configuration Java
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - senelec-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api-docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Base de données PostgreSQL (optionnelle pour le développement)
  postgres:
    image: postgres:15-alpine
    container_name: senelec-postgres
    environment:
      - POSTGRES_DB=senelec
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - senelec-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d senelec"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin pour gérer la base de données (optionnel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: senelec-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@senelec.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - senelec-network

volumes:
  postgres_data:
    driver: local

networks:
  senelec-network:
    driver: bridge 