spring:
  application:
    name: senelec-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dawn-flower-a4jfwa7h-pooler.us-east-1.aws.neon.tech/senelec?sslmode=require&channel_binding=require
    username: Freak_owner
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs 
